Feature homekitchen tests
operep/birmingham-dev-academy pull request #22
Opened 2019-08-28 20:19 UTC by Valkrys

2019-08-28 20:37 UTC, b-smyth commented
Some files deleted here Jana. If this is merged some peoples work today will be gone.

2019-08-29 14:57 UTC, lewisbirks requested changes
Seems good

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +import com.sun.imageio.plugins.wbmp.WBMPImageReader;
Unused import, can delete

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +    private String reviewProductListLocator = "//div[@class=\"sg-col-20-of-24 s-result-item sg-col-0-of-12 sg-col-28-of-32 sg-col-16-of-20 sg-col sg-col-32-of-36 sg-col-12-of-16 sg-col-24-of-28\"]";
Unused, can delete

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +    private String sortByLocator = "//*[@id=\"s-result-sort-select\"]";
Unused, can delete

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +    protected WebElement sortBy;
Unused, can delete

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +        public boolean isGlobalStoreSectionThere() {
This method is indented differently compared to the rest.

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +        if (menuText.equals(secondMenuTitle)) {
Line 85 - 88 can be simplified to `return menuText.equals(secondMenuTitle);`

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +        boolean check = false;
Unused, can remove

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +        } catch (org.openqa.selenium.NoSuchElementException e) {
Don't need the fully qualified name. Just import the `NoSuchElementException`.

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomeKitchen.java
> +            } catch (org.openqa.selenium.NoSuchElementException e) {
Don't need the fully qualified name. Just import the `NoSuchElementException`.

2019-08-29 14:57 UTC, lewisbirks commented on src/main/java/com/sampleweb/pages/HomePage.java
> +        getSearchField().sendKeys(" ");
could maybe use `.clear()` instead of `.sendKeys(" ")`

2019-11-20 09:29 UTC, closed without merging